<h4>List</h4>

In [1]:
my_list = ['banana', 'apple', 'orange']

In [5]:
print("This is my List {}".format(my_list))

This is my List ['banana', 'apple', 'orange']


In [6]:
my_list.pop()

'orange'

In [7]:
print(my_list)

['banana', 'apple']


In [8]:
my_list.append("orange")
print(my_list)

['banana', 'apple', 'orange']


In [10]:
my_list.reverse()
print(my_list)

['banana', 'apple', 'orange']


In [11]:
new_list = sorted(my_list)
print(new_list)

['apple', 'banana', 'orange']


In [12]:
my_list1 = [0]* 5
print(my_list1)

[0, 0, 0, 0, 0]


<h4> Slicing </h4>

In [20]:
my_list2 = [1, 2, 3, 4, 5]
a = my_list2[1:5]
print(a)
b = my_list2[:]
print(b)
c = my_list2[::2]
print(c)

[2, 3, 4, 5]
[1, 2, 3, 4, 5]
[1, 3, 5]


<h4> List Comphrehension </h4>

In [22]:
a = [1, 2, 3, 4, 5]
b = [i*i for i in a]
print(a)
print(b)

[1, 2, 3, 4, 5]
[1, 4, 9, 16, 25]


<h4>Tuples</h4>

In [29]:
my_tup = ("Max", "28", "Boston")
print(my_tup)
print(type(my_tup))
my_tup1 = tuple(["max", "22", "Bos"])
print(my_tup1)
print(type(my_tup1))

('Max', '28', 'Boston')
<class 'tuple'>
('max', '22', 'Bos')
<class 'tuple'>


In [30]:
my_tup[0] = "Tim" #tuple is immutable

TypeError: 'tuple' object does not support item assignment

In [31]:
for i in my_tup:
    print(i)

Max
28
Boston


In [33]:
if "Max" in my_tup:
    print("Y")
else:
    print("N")

Y


<h4>Dicitionairise</h4>

In [38]:
#update dict
my_dict1 = {"name":"Max", "age":28, "city":"Boston"}
my_dict2 = {"email":"123@email.com"}
my_dict1.update(my_dict2)
print(my_dict2)
print(my_dict1)

{'email': '123@email.com'}
{'name': 'Max', 'age': 28, 'city': 'Boston', 'email': '123@email.com'}


<h4>Set</h4>

Not allow duplicate element, unorder, mutable

In [54]:
set1 = {1, 2, 3, 4, 1, 2}
print(set1)
print(type(set1))

{1, 2, 3, 4}
<class 'set'>


In [53]:
my_list = set({1, 2, 3})
print(my_list)
my_list = set("hello")
print(my_list) #unorder
print(len(my_list))#give distinct value cause not allow dup

{1, 2, 3}
{'e', 'h', 'l', 'o'}
4


<h4> String </h4>
ordered, immutable, text represent

In [90]:
my_str = "hello"
my_str1 = "  i'm a pro  "
print(type(my_str1))
print(my_str)

<class 'str'>
hello


In [86]:
#slicing operator
sub_str_all_notinclude_last = my_str[:-1]
#from index[0] to index[-1] but not include index[-1]
sub_str_reverse = my_str[::-1]
print(sub_str_all_notinclude_last)
print(sub_str_reverse)
str_strip = my_str1#this will not change cause string
#is immutable so you need to assign to the original var
print(str_strip)
print(my_str1)
print(my_str1.find(" "))
print(my_str1.count("o"))
print(my_str1.replace("i'm", "I'm"))
print(my_str1)
print(my_str1.replace("i'm", "I'm"))
my_str1 = my_str1
print(type(my_str1))

hell
olleh
["i'm", 'a', 'pro']
["i'm", 'a', 'pro']


AttributeError: 'list' object has no attribute 'find'

In [92]:
my_str = ''.join(my_str1)
print(my_str)

  i'm a pro  


In [93]:
name = 'Jack'
print(f'My name is {name}') #f-formating 
#instead of .format

My name is Jack


<h4> Collections </h4>

In [96]:
from collections import Counter

In [100]:
a = 'aaaacccbbb'
my_counter = Counter(a)
print(my_counter)
print("As you can see its create a dictionaries")
print(my_counter.items())
print(my_counter.keys())
print(my_counter.values())

Counter({'a': 4, 'c': 3, 'b': 3})
As you can see its create a dictionaries
dict_items([('a', 4), ('c', 3), ('b', 3)])
dict_keys(['a', 'c', 'b'])
dict_values([4, 3, 3])


In [109]:
print(f'this is the most common element {my_counter.most_common(1)}')

this is the most common element [('a', 4)]


In [116]:
my_counter.most_common(1)[0]
my_counter

Counter({'a': 4, 'c': 3, 'b': 3})

In [119]:
from collections import namedtuple

In [125]:
Point = namedtuple("Point","x,y")
pt = Point(1, -4)
print(type(pt))
print(pt)
print(pt.x, pt.y)

<class '__main__.Point'>
Point(x=1, y=-4)
1 -4


<h4>Itertools</h4>
'collection of tools which handle iteration'

In [136]:
from itertools import product
a = [1, 2]
b = [3, 4]
prod = product(a,b) #return cartesian product
print(list(prod))
prod = product((a,b), repeat= 2)
print(list(prod))

[(1, 3), (1, 4), (2, 3), (2, 4)]
[([1, 2], [1, 2]), ([1, 2], [3, 4]), ([3, 4], [1, 2]), ([3, 4], [3, 4])]


In [143]:
from itertools import permutations
a = [1, 2, 3]
perm = permutations(a, 2) #return all possible permutation with lenght
print(list(perm))

[(1, 2), (1, 3), (2, 1), (2, 3), (3, 1), (3, 2)]


In [144]:
from itertools import combinations
a = [2, 4, 5, 6]
com = combinations(a, 2) #return all possible combinations with lenght 2
print(list(com))

[(2, 4), (2, 5), (2, 6), (4, 5), (4, 6), (5, 6)]


In [157]:
from itertools import accumulate
import operator
a = [1, 2, 3, 4]
accum = accumulate(a, func=operator.mul)
print(a)
print(list(accum))

[1, 2, 3, 4]
[1, 2, 6, 24]


In [163]:
from itertools import groupby
def smaller_than_3(x):
    return x < 3

a = [1, 2, 3, 4]
group_obj = groupby(a, key = smaller_than_3)
for key,value in group_obj:
    print(key, list(value))

True [1, 2]
False [3, 4]


In [167]:
persons = [{'name':'Tim', 'age': 28}, {'name':'Ben', 'age': 22}
          ,{'name': 'Jack', 'age': 12}]

In [171]:
group_obj = groupby(persons, key=lambda x:x['age']>12)
for key, value in group_obj:
    print(key, list(value))

True [{'name': 'Tim', 'age': 28}, {'name': 'Ben', 'age': 22}]
False [{'name': 'Jack', 'age': 12}]


In [176]:
#small one line function that don't have name 
#this will create a function with some argument
#then evaluate the expression after that output the result 
add10 =  lambda x:x+10
print(add10(5))

15


In [177]:
def add10_funct(x):
    return x + 10

In [179]:
add10_funct(5)

15

In [180]:
mul3 = lambda x, y: x*y
print(mul3(2, 3))

6


In [181]:
#Sorted function with lambda
point2D = [(1, 2), (-3, 4), (5, -6)]

In [184]:
point2D_sorted = sorted(point2D)
print(point2D_sorted)
point2D_sorted = sorted(point2D, key = lambda x: x[1]) #sort by x 
print(point2D_sorted)

[(-3, 4), (1, 2), (5, -6)]
[(5, -6), (1, 2), (-3, 4)]


In [189]:
#map function
#map(func, seq)
a = [1, 2, 3 , 4]
b = [3, 2, 4, 5]
c = map(lambda x: x+2, b+a)
print(list(c))

[5, 4, 6, 7, 3, 4, 5, 6]


<h4>Exception and Error </h4>

In [3]:
a = 5 print(a) #syntax error
print(a)) #syntax error

SyntaxError: invalid syntax (<ipython-input-3-9e5d7374645d>, line 1)

In [5]:
a = 5 + '10' #TypeError

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [6]:
import somemodule # moduleNotFoundError (subclass of import error)

ModuleNotFoundError: No module named 'somemodule'

In [7]:
a = 6
b = c #name error

NameError: name 'c' is not defined

In [8]:
f = open('somefile.txt')#file not found error

FileNotFoundError: [Errno 2] No such file or directory: 'somefile.txt'

In [11]:
a = [1, 2, 3]
a.remove(1)
print(a)
a.remove(4) #Value error

[2, 3]


ValueError: list.remove(x): x not in list

In [13]:
print(a[4]) #index Error

IndexError: list index out of range

In [15]:
a = {'name':'max'}
a['name']
a['key'] #Key error

KeyError: 'key'

In [16]:
x = -5
if x < 0:
    raise Exception('x should be positive')

Exception: x should be positive

In [22]:
x = 5
assert(x>=0), 'x is not positve' #execute when arguement is not true

In [24]:
x = -1
assert(x>=0), 'x is not positive' #assert error

AssertionError: x is not positive

In [26]:
a = 5 / 0 #division zero error

ZeroDivisionError: division by zero

In [27]:
#Try except blog
try:
    a = 5/0
except:
    print("An error happened")

An error happened


In [28]:
try:
    a = 5/0
except Exception as e: #Catch what error occured
    print(e)

division by zero


In [34]:
try:
    a = 5/1
    b = a + '10'
except ZeroDivisionError as e:
    print(e)
except TypeError as e:
    print(e)

unsupported operand type(s) for +: 'float' and 'str'


In [37]:
try:
    a = 5/0
    b = a + 4
except ZeroDivisionError as e:
    print(e)
except TypeError as e:
    print(e)
else:
    print("everything is fine")
finally:#run always this is for clean up operation
    print('Cleaning up...')

division by zero
Cleaning up...


In [46]:
class ValueTooHighError(Exception):
    pass
class ValueTooSmallError(Exception):
    def __init__(self, message, value):
        self.message = message
        self.value = value
def test_value(x):
    if x > 100:
        raise ValueTooHighError('value too high')
    if x < 5:
        raise ValueTooSmallError('value too small')
try:
    test_value(200)
except ValueTooHighError as e:
    print(e)
except ValueTooSmallError as e:
    print(e.message, e.value)

value too high


<h4> JSON </h4>
JSON is a short for javascript object notation
Lightweight data format
Usually use in web application

In [53]:
#Convert dictionaries to json format this call encording
person = {'name': 'Michael', 'age': 23, 'city':'North Dakhota' ,'has child':True,'title':
          ['engineer', 'doctor', 'programmer']}

In [54]:
import json

In [59]:
#dumps: stand for string
personJSON = json.dumps(person, indent=4, sort_keys = True) #encord to json format
print(personJSON) #sort key to sort key ASC

{
    "age": 23,
    "city": "North Dakhota",
    "has child": true,
    "name": "Michael",
    "title": [
        "engineer",
        "doctor",
        "programmer"
    ]
}


In [62]:
#decording convert josn to dics
person = json.loads(personJSON) #loads; s stand for string
print(person)

{'age': 23, 'city': 'North Dakhota', 'has child': True, 'name': 'Michael', 'title': ['engineer', 'doctor', 'programmer']}


In [63]:
with open('person.json', 'r') as file:
    person = json.load(file)
    print(person)

{'name': 'Michael', 'age': 23, 'city': 'North Dakhota', 'has child': True, 'title': ['engineer', 'doctor', 'programmer']}


In [64]:
class User():
    def __init__(self, name, age):
        self.name = name
        self.age = age

user = User('Max', 21)
userJSON = json.dumps(user)
#This give error

TypeError: Object of type User is not JSON serializable

In [74]:
class User():
    def __init__(self, name, age):
        self.name = name
        self.age = age

user = User('Max', 21)

def encode_user(o):
    if isinstance(o, User):
        return {'name': o.name, 'age': o.age, o.__class__.__name__:True}
    else:
        raise TypeError('Object of')
userJSON = json.dumps(user, default=encode_user)
print(userJSON)

{"name": "Max", "age": 21, "User": true}


<h4> Random number</h4>

In [86]:
import random
a= random.random()#default [0,1]
b = random.randint(1, 10)
c = random.randrange(1, 10)
d = random.normalvariate(0,1)
print(a)
print(b)
print(c)
print(d)

0.4087118434118937
9
3
0.2822726436465713


In [92]:
my_list = list("ABCDEFG")
print(my_list)

['A', 'B', 'C', 'D', 'E', 'F', 'G']


In [101]:
a = random.choice(my_list) #pick rand element
print(a)
b = random.sample(my_list, 3) #pick more than 1
print(b)

B
['E', 'G', 'D']


In [104]:
import numpy as np
import secrets

In [106]:
a = secrets.choice(my_list)
print(a)

D


In [113]:
#array with rand float
a = np.random.rand(1,3)
print(a)
b = np.random.randint(0, 10, (3,4))
print(b)

[[0.77072663 0.04520006 0.83523932]]
[[9 0 0 7]
 [6 9 0 4]
 [5 4 1 8]]


<h4> Decorators </h4>